name = "Northbound Valley"
author = "Ozoku"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48f28fc21d660b0a3907b7038b1d2aa2e6c911d163c013718e9d769354c568bf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
