name = "Northbound Valley"
author = "Ozoku"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f48d20efd39c7a2257c665f5cffade2ce9eab2e91b1a90916a7388b574960d01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.137"
