name = "Northbound Valley"
author = "Ozoku"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e3a2ff03c8ae64cadf8a59370696608c904ca6a93a405140c1817ba211822be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
