name = "Northbound Valley"
author = "Ozoku"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe88c44a196f2974744b55fab6d032053619f25c4049e0bdfca71a7c7690e88"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
