name = "Northbound Valley"
author = "Ozoku"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fde24050a57a78a0f252ac14144fb9cd023e0c00089452e8c9324b2c0bdbddcc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.128"
