name = "Northbound Valley"
author = "Ozoku"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53f9c1b9662dafb76edb07f0d8b05040df692fe031f21accd45f4aff8a6481a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.137"
